spring:
    application:
        name: Kafka-ClickHouse
    datasource:
#        url: jdbc:clickhouse://localhost:8123/kafka?compress=0
#        username: default
#        password: ""
        url: jdbc:clickhouse://localhost:8123/kafka?user=default&password=&compress=false
        driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
    data:
        redis:
            host: localhost
            port: 6379
    kafka:
        bootstrap-servers: localhost:9092
        properties:
            schema.registry.url: http://localhost:8081
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer:  io.confluent.kafka.serializers.KafkaAvroDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer:  io.confluent.kafka.serializers.KafkaAvroSerializer
server:
    tomcat:
        threads:
            max: 1000
        accept-count: 2000
